import { z } from 'zod'
import type { ErrorPayload } from './errors'
import { LanguageCodeSchema, SourceLanguageSchema, TranslationModeSchema } from './translation'

/** IPC channel names. Preload only exposes these via domain APIs. */
export const IPC = {
  translate: 'translation:translate',
  translateStream: 'translation:translate-stream',
  streamChunk: 'translation:stream-chunk',
  streamCancel: 'translation:stream-cancel',
  save: 'translation:save',
  getRecord: 'history:get',
  historyList: 'history:list',
  historyUpdate: 'history:update',
  historyDelete: 'history:delete',
  historyRestore: 'history:restore',
  historyAnalyze: 'history:analyze',
  memoryList: 'memory:list',
  memoryUpdate: 'memory:update',
  memoryDelete: 'memory:delete',
  glossaryList: 'glossary:list',
  glossaryAdd: 'glossary:add',
  glossaryRemove: 'glossary:remove',
  trainingGetToday: 'training:get-today',
  trainingSubmit: 'training:submit',
  providerTest: 'provider:test',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  settingsChooseVault: 'settings:choose-vault',
  indexRebuild: 'index:rebuild',
} as const

/** Every IPC reply is an explicit result envelope — never a thrown raw error. */
export type IpcResult<T> = { ok: true; data: T } | { ok: false; error: ErrorPayload }

export const TranslateRequestSchema = z.object({
  text: z.string().min(1).max(20000),
  sourceLanguage: SourceLanguageSchema,
  targetLanguage: LanguageCodeSchema,
  mode: TranslationModeSchema,
})

export type TranslateRequest = z.infer<typeof TranslateRequestSchema>

/**
 * Streaming translate request. The requestId is generated by the
 * renderer so stream-chunk events and cancellation can be correlated
 * without an extra round trip.
 */
export const TranslateStreamRequestSchema = TranslateRequestSchema.extend({
  requestId: z.string().min(8).max(64),
})

export type TranslateStreamRequest = z.infer<typeof TranslateStreamRequestSchema>

export const UsageSchema = z.object({
  promptTokens: z.number().int().min(0),
  completionTokens: z.number().int().min(0),
  totalTokens: z.number().int().min(0),
})

export type Usage = z.infer<typeof UsageSchema>

export const TranslateResultSchema = z.object({
  translatedText: z.string().min(1),
  provider: z.string().min(1),
  model: z.string().min(1),
  /** Id of the provider profile that served the request (failover indicator). */
  providerId: z.string().optional(),
  usage: UsageSchema.optional(),
  /** Core time from translation start until the first non-empty stream delta. */
  firstTokenMs: z.number().int().min(0).optional(),
  durationMs: z.number().int().min(0),
})

export type TranslateResult = z.infer<typeof TranslateResultSchema>

/** Lightweight connectivity/model test for the settings page. */
export const TestProviderRequestSchema = z.object({
  /** When set and no apiKey is pasted, the stored key for this id is used. */
  providerId: z.string().min(1).max(64).optional(),
  baseUrl: z.url(),
  models: z.array(z.string().min(1).max(200)).min(1).max(20),
  apiKey: z.string().min(1).max(1000).optional(),
  timeoutMs: z.number().int().min(1000).max(120000).default(15000),
})

export type TestProviderRequest = z.infer<typeof TestProviderRequestSchema>

export const TestProviderResultSchema = z.object({
  ok: z.boolean(),
  /** The model that answered, when one succeeded. */
  model: z.string().optional(),
  latencyMs: z.number().int().min(0),
  /** Per-model outcomes, in attempt order (no message content). */
  attempts: z
    .array(z.object({ model: z.string(), ok: z.boolean(), code: z.string().optional(), message: z.string().optional() }))
    .default([]),
})

export type TestProviderResult = z.infer<typeof TestProviderResultSchema>

export const SaveRequestSchema = z.object({
  sourceText: z.string().min(1).max(50000),
  aiTranslation: z.string().min(1).max(100000),
  /** Final text after user editing; omit when unchanged. */
  userTranslation: z.string().max(100000).optional(),
  sourceLanguage: SourceLanguageSchema,
  targetLanguage: LanguageCodeSchema,
  mode: TranslationModeSchema,
  provider: z.string().min(1),
  model: z.string().min(1),
  tags: z.array(z.string().min(1).max(64)).max(20).optional(),
  notes: z.string().max(20000).optional(),
})

export type SaveRequest = z.infer<typeof SaveRequestSchema>

export const SaveResultSchema = z.object({
  id: z.string().min(1),
  filePath: z.string().min(1),
})

export type SaveResult = z.infer<typeof SaveResultSchema>

export const GetRecordRequestSchema = z.object({
  id: z.string().min(1).max(200),
})

export type GetRecordRequest = z.infer<typeof GetRecordRequestSchema>
